import 'package:ecommerce_app/core/localization/language_globale_var.dart';

class ARLanguage {
  static Map<String, String> arLanguage = {
    LanguageGlobaleVar.skip: "تخطي",
    LanguageGlobaleVar.next: "التالي",
    LanguageGlobaleVar.onboardingtitle1: "توصيل الطعام",
    LanguageGlobaleVar.onboardingdesc1:
        "اطلب طعامك المفضل ببضع نقرات فقط! \nتوصيل سريع، وجبات طازجة، في أي وقت، وفي أي مكان.",
    LanguageGlobaleVar.onboardingtitle2: "سهل الدفع",
    LanguageGlobaleVar.onboardingdesc2:
        "دفع سريعة وآمن وخالي من المتاعب.\n خيارات دفع متعددة لراحتك!",
    LanguageGlobaleVar.onboardingtitle3: "توصيل سريع",
    LanguageGlobaleVar.onboardingdesc3:
        "توصيل سريع كالبرق، مباشرة إلى باب منزلك!\n طازج، ساخن، ودائما في الوقت المحدد.",
    LanguageGlobaleVar.welcomeDesc:
        "هل تشتهي شيئًا لذيذًا؟ اطلب بسهولة!\nتوصيل سريع، دفعات ميسرة، وخيارات طعام لا حصر لها بانتظارك!",
    LanguageGlobaleVar.login: "تسجيل الدخول",
    LanguageGlobaleVar.signUp: "انشاء حساب",
    LanguageGlobaleVar.loginTitle: "مرحبا!",
    LanguageGlobaleVar.signUpTitle: "حساب جديد",
    LanguageGlobaleVar.welcome: "مرحبا",
    LanguageGlobaleVar.email: "ايميل",
    LanguageGlobaleVar.enterEmailHere: "ادخل الايميل هنا",
    LanguageGlobaleVar.password: "الباسورد",
    LanguageGlobaleVar.fullname: "الاسم كامل",
    LanguageGlobaleVar.enterFullnamehere: "ادخل الاسم كامل هنا",
    LanguageGlobaleVar.mobileNumber: "رقم الموبايل",
    LanguageGlobaleVar.confirmPassword: "تاكيد الباسورد",
    LanguageGlobaleVar.pleaseenteryouremail: "رجاءا ادخال ايميلك!",
    LanguageGlobaleVar.pleaseentervalidateemail: "رجاءا ادخال ايميل صحيح",
    LanguageGlobaleVar.pleaseenteryourMobile: "رجاءا ادخال رقمك المحمول!",
    LanguageGlobaleVar.pleaseentervalidateMobile: "رجاءا ادخال رقم تليفون صحيح",
    LanguageGlobaleVar.pleaseenteryourpassword: "رجاءا ادخال باسورد!",
    LanguageGlobaleVar.pleaseentervalidatepassword:
        "يجب أن تتكون كلمة المرور من 8 أحرف على الأقل وتتضمن حرفًا كبيرًا واحدًا على الأقل وحرفًا صغيرًا واحدًا ورقمًا واحدًا وحرفًا خاصًا واحدًا (@\$!%?&)",
    LanguageGlobaleVar.pleaseenteryourFullName: "رجاءا ادخال اسمك كامل",
    LanguageGlobaleVar.pleaseentervalidateFullName:
        "علي الاقل اسم مكون من 6 حروف!",
    LanguageGlobaleVar.pleaseentervalidateconfirmpassword: "ادخل باسور متشابه!",
    LanguageGlobaleVar.privacy1: "من خلال الاستمرار فإنك توافق على ",
    LanguageGlobaleVar.privacy2: "شروط الاستخدام ",
    LanguageGlobaleVar.privacy3: "سياسة الخصوصية.",
    LanguageGlobaleVar.and: "و ",
    LanguageGlobaleVar.search: "بحث",
    LanguageGlobaleVar.goodMorning: "صباح الخير",
    LanguageGlobaleVar.riseandshine: "استيقظوا! حان وقت الإفطار",
    LanguageGlobaleVar.bestSeller: "الافضل مبيعا ",
    LanguageGlobaleVar.viewAll: "مشاهدت الكل",
    LanguageGlobaleVar.recommend: "توصية",
    LanguageGlobaleVar.snacks: "تسليه",
    LanguageGlobaleVar.meal: "وجبات",
    LanguageGlobaleVar.vegan: "Vegan",
    LanguageGlobaleVar.dessert: "نباتي",
    LanguageGlobaleVar.drinks: "مشروبات",
    LanguageGlobaleVar.addtoCart: "اضف الي المحفظة",
    LanguageGlobaleVar.myProfile: "صفحتك",
    LanguageGlobaleVar.myFavorites: "مفضلتي",
    LanguageGlobaleVar.myOrders: "طلباتي",
    LanguageGlobaleVar.settings: "اعدادات",
    LanguageGlobaleVar.logOut: "تسجيل الخروج",
    LanguageGlobaleVar.language: "اللغة",
    LanguageGlobaleVar.error: "حدث خطأ",
    LanguageGlobaleVar.success: "عملية صحيحه",
    LanguageGlobaleVar.update: "تحديث",
  };
}
