import 'package:ecommerce_app/core/localization/language_globale_var.dart';

class ENLanguage {
  static Map<String, String> enLanguage = {
    LanguageGlobaleVar.skip: "Skip",
    LanguageGlobaleVar.next: "Next",
    LanguageGlobaleVar.onboardingtitle1: "Order For Food",
    LanguageGlobaleVar.onboardingdesc1:
        "Order your favorite food in just a few taps!\nFast delivery, fresh meals, anytime, anywhere.",
    LanguageGlobaleVar.onboardingtitle2: "Easy Payment",
    LanguageGlobaleVar.onboardingdesc2:
        "Fast, secure, and hassle-free payments.\nMultiple payment options for your convenience!",
    LanguageGlobaleVar.onboardingtitle3: "Fast Delivery",
    LanguageGlobaleVar.onboardingdesc3:
        "Lightning-fast delivery, right to your doorstep!\nFresh, hot, and always on time.",
    LanguageGlobaleVar.welcomeDesc:
        "Craving something delicious? Order with ease!\nFast delivery, easy payments, and endless food choices await you!",
    LanguageGlobaleVar.login: "Log In",
    LanguageGlobaleVar.signUp: "Sign Up",
    LanguageGlobaleVar.loginTitle: "Hello!",
    LanguageGlobaleVar.signUpTitle: "New Account",
    LanguageGlobaleVar.welcome: "Welcome",
    LanguageGlobaleVar.email: "Email",
    LanguageGlobaleVar.enterEmailHere: "Enter email here",
    LanguageGlobaleVar.password: "Password",
    LanguageGlobaleVar.fullname: "Full name",
    LanguageGlobaleVar.enterFullnamehere: "Enter Full name here",
    LanguageGlobaleVar.mobileNumber: "Mobile Number",
    LanguageGlobaleVar.confirmPassword: "Confirm Password ",
    LanguageGlobaleVar.pleaseenteryouremail: "Please Enter Your Email!",
    LanguageGlobaleVar.pleaseentervalidateemail: "Please Enter Validate Email!",
    LanguageGlobaleVar.pleaseenteryourMobile:
        "Please Enter Your Mobile Number!",
    LanguageGlobaleVar.pleaseentervalidateMobile:
        "Please Enter Validate Mobile  Number!",
    LanguageGlobaleVar.pleaseenteryourpassword: "Please Enter Your Password!",
    LanguageGlobaleVar.pleaseentervalidatepassword:
        "Password must be at least 8 characters long and include at least one uppercase letter, one lowercase letter, one number, and one special character (@\$!%?&)",
    LanguageGlobaleVar.pleaseenteryourFullName: "Please Enter Your Full Name!",
    LanguageGlobaleVar.pleaseentervalidateFullName:
        "Please Enter at least 6 character!",
    LanguageGlobaleVar.pleaseentervalidateconfirmpassword:
        "Please Enter Password Match!",
    LanguageGlobaleVar.privacy1: "By continuing, you agree to ",
    LanguageGlobaleVar.privacy2: "Terms of Use ",
    LanguageGlobaleVar.privacy3: "Privacy Policy.",
    LanguageGlobaleVar.and: "and ",
    LanguageGlobaleVar.search: "Search",
    LanguageGlobaleVar.goodMorning: "Good Morning",
    LanguageGlobaleVar.riseandshine: "Rise and shine! It's breakfast time",
    LanguageGlobaleVar.bestSeller: "Best Seller ",
    LanguageGlobaleVar.viewAll: "View All",
    LanguageGlobaleVar.recommend: "Recommend",
    LanguageGlobaleVar.snacks: "Snacks",
    LanguageGlobaleVar.meal: "Meal",
    LanguageGlobaleVar.vegan: "Vegan",
    LanguageGlobaleVar.dessert: "Dessert",
    LanguageGlobaleVar.drinks: "Drinks",
    LanguageGlobaleVar.addtoCart: "Add to Cart",
    LanguageGlobaleVar.myProfile: "My Profile",
    LanguageGlobaleVar.myFavorites: "My Favorites",
    LanguageGlobaleVar.myOrders: "My Orders",
    LanguageGlobaleVar.settings: "Settings",
    LanguageGlobaleVar.logOut: "Log Out",
    LanguageGlobaleVar.language: "Language",
    LanguageGlobaleVar.error: "Error",
    LanguageGlobaleVar.success: "Success",
    LanguageGlobaleVar.update: "Update",
    LanguageGlobaleVar.card: "Card",
    LanguageGlobaleVar.confirmOrder: "Confirm Order",
    LanguageGlobaleVar.orderDetails: "Order Details",
    LanguageGlobaleVar.active: "Active",
    LanguageGlobaleVar.completed: "Completed",
    LanguageGlobaleVar.cancelled: "Cancelled",
    LanguageGlobaleVar.searchAbout: "search about what you want",
    LanguageGlobaleVar.subtotal: "Subtotal",
    LanguageGlobaleVar.taxAndFees: "Tax and Fees",
    LanguageGlobaleVar.delivery: "Delivery",
    LanguageGlobaleVar.total: "Total",
  };
}
